{ inputs, ... }:
{
  flake.modules.nixos.default =
    { username, ... }:
    {
      sops.secrets."intelephense/licence-key".owner = username;
      sops.secrets."openrouter/api-key".owner = username;
    };

  flake.modules.homeManager.default =
    {
      pkgs,
      config,
      lib,
      osConfig,
      palette,
      identity,
      ...
    }:
    let
      lispString = builtins.toJSON;
      lispStrings = strings: "(${lib.concatMapStringsSep " " lispString strings})";

      mailAccounts = lib.sort (a: b: a.primary && !b.primary) (
        lib.attrValues config.accounts.email.accounts
      );
      primaryMail = builtins.head mailAccounts;
      mailAccountLisp =
        account:
        "(:name ${lispString account.name} :address ${lispString account.address}"
        + " :aliases ${lispStrings account.aliases} :signature ${lispString account.signature.text}"
        + " :maildir ${lispString account.maildir.path} :key ?${identity.mail.${account.name}.key})";

      doomOnlyPackages =
        builtins.attrValues {
          inherit (pkgs)
            curl
            graphviz
            jre
            languagetool
            pandoc
            plantuml

            intelephense
            laravel-lsp
            marksman
            tailwindcss-language-server
            typescript-language-server
            vscode-langservers-extracted

            blade-formatter
            html-tidy
            js-beautify
            nixfmt
            prettier
            shellcheck
            shfmt
            sops
            stylelint

            # :app everywhere
            wl-clipboard
            wtype
            ;
        }
        ++ [
          pkgs.libxml2.bin # xmllint, for `:lang data' XML formatting
          pkgs.python3Packages.weasyprint
          (pkgs.texliveSmall.withPackages (
            ps:
            builtins.attrValues {
              inherit (ps)
                wrapfig
                capt-of
                ulem
                footnotehyper
                xurl
                upquote
                ;
            }
          ))
        ];
      dapeAdapterDir = pkgs.runCommandLocal "dape-adapters" { } ''
        mkdir -p $out/php-debug
        ln -s ${pkgs.vscode-extensions.xdebug.php-debug}/share/vscode/extensions/xdebug.php-debug \
              $out/php-debug/extension
      '';
    in
    {
      imports = [ inputs.nix-doom-emacs-unstraightened.homeModule ];

      programs.doom-emacs = {
        enable = true;
        emacs = pkgs.emacs-pgtk;

        doomDir = pkgs.runCommandLocal "doomdir" { } ''
          cp -r ${../../doom} $out
          chmod -R u+w $out
          cat > $out/lisp/my-nix-paths.el <<'EOF'
          ;;; my-nix-paths.el --- generated by doom-emacs.nix -*- lexical-binding: t; -*-
          (defconst my/font-mono ${lispString palette.fonts.mono})
          (defconst my/font-emoji ${lispString palette.fonts.emoji})
          (defconst my/font-size ${toString palette.fonts.sizes.terminal})
          (defconst my/full-name ${lispString primaryMail.realName})
          (defconst my/mail-address ${lispString primaryMail.address})
          (defconst my/mail-accounts
            '(${lib.concatMapStringsSep "\n    " mailAccountLisp mailAccounts}))
          (defconst my/dape-adapter-dir "${dapeAdapterDir}/")
          (defconst my/openrouter-key-file "${osConfig.sops.secrets."openrouter/api-key".path}")
          (defconst my/intelephense-key-file "${osConfig.sops.secrets."intelephense/licence-key".path}")
          (provide 'my-nix-paths)
          EOF
        '';

        extraPackages = epkgs: [
          epkgs.vterm
          epkgs.treesit-grammars.with-all-grammars
        ];

        extraBinPackages =
          builtins.attrValues {
            inherit (pkgs)
              fd
              git
              ripgrep
              ;
          }
          ++ doomOnlyPackages;
      };

      services.emacs.enable = true;
      services.emacs.socketActivation.enable = true;
    };
}
